eureka:
  client:
    service-url:
      defaultZone: http://localhost:8076/eureka
    register-with-eureka: true
    fetch-registry: true

server:
  port: 9091

spring:
  application:
    name: "questionnaire-service"
