eureka:
  client:
    service-url:
      defaultZone: http://localhost:8076/eureka
    register-with-eureka: true
    fetch-registry: true

server:
  port: 8086


spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            exposedHeaders: "*"

      routes:
        - id: wellness-tracker-service
          uri: http://localhost:8083/
          predicates:
            - Path=/wellness-tracker-service/**
          filters:
            - RewritePath=/wellness-tracker-service(?<segment>/?.*), $\{segment}

        - id: nlp-service
          uri: http://localhost:8098/
          predicates:
            - Path=/nlp-service/**
          filters:
            - RewritePath=/nlp-service(?<segment>/?.*), $\{segment}

        - id: plan-payment-service
          uri: http://localhost:8096/
          predicates:
            - Path=/plan-payment-service/**
          filters:
            - RewritePath=/plan-payment-service(?<segment>/?.*), $\{segment}

        - id: graph-command-service
          uri: http://localhost:9092/
          predicates:
            - Path=/graph-command-service/**
          filters:
            - RewritePath=/graph-command-service(?<segment>/?.*), $\{segment}

        - id: graph-query-service
          uri: http://localhost:8097/
          predicates:
            - Path=/graph-query-service/**
          filters:
            - RewritePath=/graph-query-service(?<segment>/?.*), $\{segment}

        - id: questionnaire-service
          uri: http://localhost:9091/
          predicates:
            - Path=/questionnaire-service/**
          filters:
            - RewritePath=/questionnaire-service(?<segment>/?.*), $\{segment}

        - id: socket-notification-service
          uri: http://localhost:8092/
          predicates:
            - Path=/socket-notification-service/**
          filters:
            - RewritePath=/socket-notification-service(?<segment>/?.*), $\{segment}

        - id: wellness-mentor-service
          uri: http://localhost:8085/
          predicates:
            - Path=/wellness-mentor-service/**
          filters:
            - RewritePath=/wellness-mentor-service(?<segment>/?.*), $\{segment}

        - id: wellness-service
          uri: http://localhost:8070/
          predicates:
            - Path=/wellness-service/**
          filters:
            - RewritePath=/wellness-service(?<segment>/?.*), $\{segment}

        - id: user-service
          uri: http://localhost:8082/
          predicates:
            - Path=/user-service/**
          filters:
            - RewritePath=/user-service(?<segment>/?.*), $\{segment}

        - id: user-auth-service
          uri: http://localhost:8080/
          predicates:
            - Path=/user-auth-service/**
          filters:
            - RewritePath=/user-auth-service(?<segment>/?.*), $\{segment}

        - id: sentiment-service
          uri: http://localhost:8090/
          predicates:
            - Path=/sentiment-service/**
          filters:
            - RewritePath=/sentiment-service(?<segment>/?.*), $\{segment}

        - id: wholesome-care-webapp
          uri: http://localhost:8099/
          predicates:
            - Path=/**
          filters:
            - RewritePath=(?<segment>/?.*), $\{segment}

