FROM openjdk:11-jre-slim
ADD target/wholesome-care-webapp-0.0.1-SNAPSHOT.jar wholesome-care-webapp-0.0.1-SNAPSHOT.jar
EXPOSE 8099
ENTRYPOINT ["java","-jar","wholesome-care-webapp-0.0.1-SNAPSHOT.jar"]
